version: '3.1'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT}
        - NODE_ENV=${ENVIRONMENT}
        - PORT=${PORT}
    environment:
      - NODE_ENV=stage
      - PORT=7005
    restart: unless-stopped
    ports:
      - "${PORT_EXPOSE}:${PORT}"
    networks:
      - mynet
networks:
  mynet: